import React, {useEffect, useMemo, useState} from 'react'
import {createRoot} from 'react-dom/client'
import {MapPinned, Route, Camera, Users, LockKeyhole, Mic, MessageCircle, Plus, Trash2, Check, ChevronDown, Plane, MapPin, ShieldCheck, Wifi, ImageIcon} from './icons.jsx'
import './styles.css'

const VERSION='0.1.0'
const cityImages={
  Delhi:'https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=1200&q=82',
  Udaipur:'https://images.unsplash.com/photo-1595658658481-d53d3f999875?auto=format&fit=crop&w=1200&q=82',
  Jodhpur:'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=1200&q=82',
  Jaipur:'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1200&q=82',
  Agra:'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=1200&q=82',
  Varanasi:'https://images.unsplash.com/photo-1561361058-c24e02d4a4c4?auto=format&fit=crop&w=1200&q=82'
}
const days=[
  ['Lun 10 ago','Delhi','Benvenuti a Delhi','Lotus Temple, Connaught Place e cena di gruppo da Unplugged Courtyard. Serata leggera per recuperare energie.',['Lotus Temple','Pranzo locale','Connaught Place','Cena e compleanni']],
  ['Mar 11 ago','Delhi','Delhi senza filtri','Sanjay Colony con associazione locale, Red Fort, Chandni Chowk, Jama Masjid e rooftop al Gumbad Café.',['Tour Sanjay Colony','Red Fort','Chandni Chowk','Jama Masjid']],
  ['Mer 12 ago','Udaipur','Verso la città dei laghi','Volo mattutino per Udaipur, passeggiata sul lago e cena elegante al Charcoal.',['Volo Delhi–Udaipur','Check-in','Passeggiata lago','Cena Charcoal']],
  ['Gio 13 ago','Udaipur','Palazzi al tramonto','Tour guidato all’alba, barca sul lago Pichola, City Palace, shopping e cena da Jagat Niwas.',['Tour guidato','Barca al tramonto','City Palace','Shopping']],
  ['Ven 14 ago','Jodhpur','Ranakpur e la città blu','Van verso Jodhpur con sosta al tempio giainista di Ranakpur, pozzo a gradini ed esperienza local.',['Partenza in van','Tempio Ranakpur','Pozzo a gradini','Cena Jhankar Haveli']],
  ['Sab 15 ago','Jodhpur','Dentro la città blu','Walking tour con Lakshimi, colazione indiana, Forte Mehrangarh e musica live al Blue Bird.',['Walking tour','Colazione tipica','Mehrangarh Fort','Musica live']],
  ['Dom 16 ago','Jaipur','Jaipur e cooking class','Trasferimento verso Jaipur, possibile sosta a Pushkar, walking tour e cooking class con Vaseem.',['Van per Jaipur','Walking tour','Cooking class','Cena insieme']],
  ['Lun 17 ago','Jaipur','Templi, scimmie e fortezze','Galta Ji al mattino, Amber Fort nel pomeriggio e cena con vista per il compleanno di Paolo.',['Galta Ji','Amber Fort','Foto di gruppo','Cena Tattoo Café']],
  ['Mar 18 ago','Agra','Prima vista sul Taj Mahal','Shopping a Jaipur, van per Agra, prima foto del Taj dal fiume e aperitivo panoramico.',['Shopping Jaipur','Van per Agra','Foto Taj Mahal','Aperitivo Joey’s']],
  ['Mer 19 ago','Agra','Il giorno del Taj Mahal','Taj Mahal all’alba con guida, mercatini, pranzo solidale da Sheroes e treno notturno per Varanasi.',['Taj Mahal all’alba','Mercatini','Pranzo Sheroes','Treno notturno']],
  ['Gio 20 ago','Varanasi','L’essenza del Gange','Arrivo, walking tour dei ghat con Pappu, cerimonia Ganga Aarti e cena al BrijRama Palace.',['Arrivo e check-in','Walking tour ghat','Ganga Aarti','Cena BrijRama']],
  ['Ven 21 ago','Varanasi','Alba sul Gange','Barca all’alba, yoga su rooftop e festa per il compleanno di Davide.',['Barca all’alba','Tempo libero','Yoga rooftop','Cena Aadha Aadha']],
  ['Sab 22 ago','Varanasi','Ultime ore e ritorno','Mattina libera, ultimi regali e treno delle 15 per Delhi con arrivo in tarda serata.',['Mattina libera','Ultimi regali','Treno per Delhi','Ultima serata']],
  ['Dom 23 ago','Delhi','Namaste India','Saluti e partenze. Per chi resta: Humayun’s Tomb e Akshardham Temple.',['Check-out','Saluti','Humayun’s Tomb opzionale','Akshardham opzionale']]
]
const route=['Delhi','Udaipur','Ranakpur','Jodhpur','Jaipur','Agra','Varanasi','Delhi']
const load=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
function App(){
 const [tab,setTab]=useState('roadmap'); const [done,setDone]=useState(()=>load('india-done',{})); const [posts,setPosts]=useState(()=>load('india-posts',[])); const [people,setPeople]=useState(()=>load('india-people',[])); const [open,setOpen]=useState(0); const [selectedDay,setSelectedDay]=useState(0)
 useEffect(()=>localStorage.setItem('india-done',JSON.stringify(done)),[done]); useEffect(()=>localStorage.setItem('india-posts',JSON.stringify(posts)),[posts]); useEffect(()=>localStorage.setItem('india-people',JSON.stringify(people)),[people])
 const completed=useMemo(()=>Object.values(done).filter(Boolean).length,[done])
 return <div className="app">
  <header className="hero"><div className="heroShade"/><div className="top"><span className="flag">🇮🇳</span><span className="brand">INDIA INSIEME</span><span className="version">REV {VERSION}</span></div><div className="heroCopy"><p>10 — 23 AGOSTO 2026</p><h1>Dal Taj Mahal<br/>all’alba sul Gange.</h1><div className="heroStats"><span><Plane size={15}/> 14 giorni</span><span><MapPinned size={15}/> 7 tappe</span><span><Users size={15}/> il nostro gruppo</span></div></div></header>
  <nav className="tabs" aria-label="Sezioni">{[['roadmap',Route,'Viaggio'],['map',MapPinned,'Mappa'],['diary',Camera,'Diario'],['people',Users,'Gruppo'],['vault',LockKeyhole,'Privato']].map(([id,I,l])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><I size={20}/><small>{l}</small></button>)}</nav>
  <main>
   {tab==='roadmap'&&<section><div className="sectionHead"><div><span className="eyebrow">LA ROADMAP</span><h2>Ogni giorno, una storia</h2></div><div className="progress"><b>{completed}</b><small>spuntate</small></div></div><div className="dayList">{days.map((d,i)=><article className="day" key={i}><button className="dayHero" onClick={()=>setOpen(open===i?-1:i)} aria-expanded={open===i}><img src={cityImages[d[1]]||cityImages.Jodhpur} alt={d[1]}/><span className="dayNo">{String(i+1).padStart(2,'0')}</span><div><small>{d[0]} · {d[1]}</small><h3>{d[2]}</h3></div><ChevronDown className={open===i?'rot':''}/></button>{open===i&&<div className="dayBody"><p>{d[3]}</p><div className="checks">{d[4].map((x,j)=>{const k=`${i}-${j}`;return <label key={k} className={done[k]?'checked':''}><input type="checkbox" checked={!!done[k]} onChange={e=>setDone({...done,[k]:e.target.checked})}/><span>{done[k]?<Check size={15}/>:null}</span>{x}</label>})}</div><button className="addStory" onClick={()=>setTab('diary')}><Camera size={18}/> Aggiungi un ricordo di oggi</button></div>}</article>)}</div></section>}
   {tab==='map'&&<section><span className="eyebrow">DAL NORD AL GANGE</span><h2>La nostra India</h2><div className="mapCard"><div className="mapGlow"/><div className="route">{route.map((x,i)=><div className="stop" key={i}><span>{i+1}</span><div><b>{x}</b><small>{i===0?'Si parte da qui':i===route.length-1?'Rientro e saluti':`Tappa ${i+1}`}</small></div>{i<route.length-1&&<i/>}</div>)}</div><div className="mapLabel"><MapPin/> 2.400+ km di meraviglia</div></div></section>}
   {tab==='diary'&&<Diary posts={posts} setPosts={setPosts} selectedDay={selectedDay} setSelectedDay={setSelectedDay}/>} 
   {tab==='people'&&<People people={people} setPeople={setPeople}/>} 
   {tab==='vault'&&<Vault people={people}/>}
  </main><footer><span>🇮🇳</span><p>Un viaggio si misura negli amici, non nei chilometri.</p><small>India Insieme · revisione {VERSION}</small></footer>
 </div>
}
function Diary({posts,setPosts,selectedDay,setSelectedDay}){const [text,setText]=useState('');const [media,setMedia]=useState(null);const add=()=>{if(!text.trim()&&!media)return;setPosts([{id:Date.now(),author:'Io',text,media,day:selectedDay,comments:[],date:new Date().toLocaleString('it-IT')},...posts]);setText('');setMedia(null)};const file=e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>25*1024*1024){alert('File troppo grande per la demo: massimo 25 MB');return}const r=new FileReader();r.onload=()=>setMedia({name:f.name,type:f.type,url:r.result});r.readAsDataURL(f)};const download=()=>{const payload={version:VERSION,exportedAt:new Date().toISOString(),posts};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='india-insieme-archivio.json';a.click();URL.revokeObjectURL(a.href)};return <section><span className="eyebrow">IL DIARIO DEL GRUPPO</span><h2>Raccontiamola insieme</h2><p className="intro">Un unico album, collegato anche alle singole giornate.</p><button className="downloadAll" onClick={download}>↓ Scarica tutto sul dispositivo</button><div className="dataSaver"><Wifi/><div><b>Modalità pochi giga</b><small>Anteprime leggere; video in coda fino al Wi‑Fi.</small></div></div><div className="composer"><select value={selectedDay} onChange={e=>setSelectedDay(Number(e.target.value))}>{days.map((d,i)=><option value={i} key={i}>Giorno {i+1} · {d[1]}</option>)}</select><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Che cosa vuoi raccontare?"/><div className="composerActions"><label><ImageIcon size={18}/> Foto<input type="file" accept="image/*" onChange={file}/></label><label><Camera size={18}/> Video<input type="file" accept="video/*" onChange={file}/></label><label><Mic size={18}/> Audio<input type="file" accept="audio/*" onChange={file}/></label><button onClick={add}><Plus size={18}/> Pubblica</button></div>{media&&<small className="selected">Allegato: {media.name}</small>}</div>{posts.length===0?<Empty icon={Camera} title="Il diario è ancora vuoto" text="Aggiungi il primo pensiero, una foto, un video o un messaggio audio."/>:posts.map(p=><Post key={p.id} p={p} posts={posts} setPosts={setPosts}/>)}</section>}
function Post({p,posts,setPosts}){const [c,setC]=useState('');const [deleting,setDeleting]=useState(false);const [code,setCode]=useState('');const [deleteError,setDeleteError]=useState('');const upd=q=>setPosts(posts.map(x=>x.id===p.id?q:x));const remove=()=>{if(code==='india26')setPosts(posts.filter(x=>x.id!==p.id));else setDeleteError('Codice non corretto')};return <article className="post"><div className="postTop"><div className="avatar">{p.author[0]}</div><div><b>{p.author}</b><small>{p.date}</small></div><button aria-label="Elimina" onClick={()=>setDeleting(!deleting)}><Trash2 size={18}/></button></div>{deleting&&<div className="deleteGate"><b>Cancellazione protetta</b><input type="password" value={code} onChange={e=>setCode(e.target.value)} placeholder="Codice del gruppo"/><button onClick={remove}>Conferma</button>{deleteError&&<small>{deleteError}</small>}</div>}{p.text&&<p>{p.text}</p>}{p.media?.type.startsWith('image')&&<img src={p.media.url} alt="Ricordo del viaggio"/>}{p.media?.type.startsWith('video')&&<video controls playsInline src={p.media.url}/>} {p.media?.type.startsWith('audio')&&<audio controls src={p.media.url}/>}<div className="comments">{p.comments.map((x,i)=><small key={i}><MessageCircle size={13}/>{x}</small>)}<div><input value={c} onChange={e=>setC(e.target.value)} placeholder="Scrivi un commento"/><button onClick={()=>{if(c.trim()){upd({...p,comments:[...p.comments,c]});setC('')}}}>Invia</button></div></div></article>}
function People({people,setPeople}){const [form,setForm]=useState({name:'',surname:'',age:'',job:'',bio:''});const add=()=>{if(!form.name)return;setPeople([...people,{...form,id:Date.now()}]);setForm({name:'',surname:'',age:'',job:'',bio:''})};return <section><span className="eyebrow">CHI PARTE CON NOI</span><h2>La nostra crew</h2><div className="profileForm"><div className="avatar big"><Users/></div><input placeholder="Nome *" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input placeholder="Cognome (facoltativo)" value={form.surname} onChange={e=>setForm({...form,surname:e.target.value})}/><div className="split"><input placeholder="Età" inputMode="numeric" value={form.age} onChange={e=>setForm({...form,age:e.target.value})}/><input placeholder="Lavoro" value={form.job} onChange={e=>setForm({...form,job:e.target.value})}/></div><textarea placeholder="Raccontaci qualcosa di te…" value={form.bio} onChange={e=>setForm({...form,bio:e.target.value})}/><button onClick={add}><Plus/> Inserisci viaggiatore</button></div><div className="peopleGrid">{people.map(x=><article key={x.id}><div className="avatar big">{x.name[0]}</div><h3>{x.name} {x.surname}</h3><small>{[x.age&&`${x.age} anni`,x.job].filter(Boolean).join(' · ')}</small><p>{x.bio}</p><button onClick={()=>setPeople(people.filter(y=>y.id!==x.id))}><Trash2 size={16}/> Rimuovi</button></article>)}</div>{!people.length&&<Empty icon={Users} title="Aggiungi la crew" text="Ogni viaggiatore potrà scegliere quali informazioni rendere visibili."/>}</section>}
function Vault({people}){const [unlocked,setUnlocked]=useState(false);const [password,setPassword]=useState('');const [error,setError]=useState('');const [position,setPosition]=useState(null);const [docs,setDocs]=useState(()=>load('india-doc-status',{}));useEffect(()=>localStorage.setItem('india-doc-status',JSON.stringify(docs)),[docs]);const unlock=()=>{if(password==='india26'){setUnlocked(true);setError('')}else setError('Codice non corretto')};const locate=()=>navigator.geolocation?.getCurrentPosition(p=>setPosition({lat:p.coords.latitude.toFixed(5),lng:p.coords.longitude.toFixed(5),at:new Date().toLocaleTimeString('it-IT')}),()=>setError('Posizione non disponibile: controlla i permessi del telefono.'));const toggle=(id,type)=>setDocs({...docs,[`${id}-${type}`]:!docs[`${id}-${type}`]});return <section><span className="eyebrow">AREA RISERVATA</span><h2>La base del gruppo</h2>{!unlocked?<div className="vault"><div className="lock"><LockKeyhole/></div><h3>Solo viaggiatori</h3><p>Inserisci il codice condiviso del gruppo per aprire la demo privata.</p><div className="unlock"><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Codice di accesso" onKeyDown={e=>e.key==='Enter'&&unlock()}/><button onClick={unlock}>Entra</button></div>{error&&<small className="error">{error}</small>}</div>:<div className="vault unlocked"><div className="privateBadge"><ShieldCheck/> Area privata aperta</div><h3>Dove siamo</h3><p>Condividi volontariamente la tua posizione attuale con il gruppo.</p><button className="locationBtn" onClick={locate}><MapPin/> Condividi posizione adesso</button>{position&&<div className="position"><b>Ultima posizione acquisita</b><span>{position.lat}, {position.lng}</span><small>Aggiornata alle {position.at}</small></div>}<h3>Controllo documenti</h3><div className="docTable"><div className="docRow head"><b>Viaggiatore</b><b>Pass.</b><b>Visto</b></div>{people.length?people.map(p=><div className="docRow" key={p.id}><span>{p.name} {p.surname}</span>{['pass','visa'].map(t=><button key={t} className={docs[`${p.id}-${t}`]?'ok':''} onClick={()=>toggle(p.id,t)} aria-label={`${t} di ${p.name}`}>{docs[`${p.id}-${t}`]?'✓':'—'}</button>)}</div>):<p className="noPeople">Inserisci prima i partecipanti nella sezione Gruppo.</p>}</div><div className="security"><span><LockKeyhole/> Passaporto</span><span><ShieldCheck/> Visto · da verificare</span><span><Plane/> Biglietti aerei</span><span><Wifi/> Assicurazione e altri file</span></div><div className="coordinator"><Users/><div><b>Controllo coordinatrice</b><small>Può verificare completezza e segnalare documenti mancanti.</small></div></div><div className="notice"><b>Modalità di collaudo</b><p>Il codice iniziale è semplice. Non caricare ancora documenti reali finché il server condiviso e la cancellazione sicura non avranno superato le prove.</p></div></div>}</section>}
function Empty({icon:I,title,text}){return <div className="empty"><I/><h3>{title}</h3><p>{text}</p></div>}
createRoot(document.getElementById('root')).render(<App/>)
